#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, find
#       out which one and use it instead.
#
#   (2) Gradle will search for your Android SDK in the following locations:
#       - ANDROID_SDK_ROOT environment variable
#       - android.sdkDirectory in local.properties
#       - sdk.dir in local.properties
#
##############################################################################

set -e

DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

# Use the maximum available, or set MAX_FD != unlimited if you use the following.
MAX_FD="maximum"

warn() {
    echo "$*" >&2
}

die() {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

# increase the memory to 256m on macos
if [ "$(uname)" = "Darwin" ]; then
    DEFAULT_JVM_OPTS="-Xmx64m"
else
    DEFAULT_JVM_OPTS="-Xmx64m"
fi

APP_NAME="Gradle"
APP_JAR="gradle-wrapper.jar"
APP_HOME="$(pwd)"

cd "$APP_HOME"

exec "$JAVACMD" $DEFAULT_JVM_OPTS -cp "gradle/wrapper/$APP_JAR" org.gradle.wrapper.GradleWrapperMain "$@"
